# general settings
name: train_SR_x2
model_type: HybridSRModel
scale: 2
#num_gpu: auto
num_gpu: 1
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /home/zhangchun/Desktop/SR_data/DF2K/HR
    dataroot_lq: /home/zhangchun/Desktop/SR_data/DF2K/LR_bicubic/X2
#    dataroot_gt: /home/zhangchun/Desktop/SR_data/DIV2K/DIV2K_train_HR/
#    dataroot_lq: /home/zhangchun/Desktop/SR_data/DIV2K/DIV2K_train_LR_bicubic_X4/DIV2K_train_LR_bicubic/X4
    filename_tmpl: '{}x2'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 12
    batch_size_per_gpu: 8
#    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    task: SR
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /home/zhangchun/Desktop/SR_data/benchmark/Set14/HR
    dataroot_lq: /home/zhangchun/Desktop/SR_data/benchmark/Set14/LR_bicubic/X2
#    dataroot_gt: /home/zhangchun/Desktop/SR_data/benchmark/Set5/HR
#    dataroot_lq: /home/zhangchun/Desktop/SR_data/benchmark/Set5/LR_bicubic/x4
    filename_tmpl: '{}x2'
    io_backend:
      type: disk


# network structures
network_g:
  type: TestModel
  upscale: 2
  in_chans: 3
  img_size: 64
  split_size: [4,4,4]
#  split_size: [1,1,1,1,1]
  depth: [3,3,3]
  num_heads: [6,6,6]
  embed_dim: 180
  mlp_ratio: 2.
  resi_connection: '1conv'

path:
  pretrain_network_g: ~
  strict_load_g: False
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
#    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 250000, 400000, 450000, 475000, 500000]
#    milestones: [ 150000, 240000, 270000, 285000, 300000 ]
    gamma: 0.5


  total_iter: 500000
#  total_iter: 350000
#  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
#  val_freq: !!float 1000
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True

# logging settings
logger:
  print_freq: !!float 1e3
  save_checkpoint_freq: !!float 10e3
  use_tb_logger: True

# dist training settings
dist_params:
  backend: nccl
  port: 29500
